# Generated by Django 3.0.6 on 2020-05-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=420)),
            ],
        ),
        migrations.CreateModel(
            name='Confesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.DecimalField(decimal_places=0, max_digits=2)),
                ('sexo', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino'), ('indefinido', 'indefinido')], default='indefinido', max_length=10)),
                ('contenido', models.TextField(max_length=420)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confesion.Comentario')),
            ],
        ),
    ]
