# Generated by Django 3.0.6 on 2020-05-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confesion',
            name='edad',
            field=models.DecimalField(decimal_places=0, max_digits=2, max_length=2),
        ),
    ]
