# Generated by Django 3.0.6 on 2020-05-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confesion', '0002_auto_20200516_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confesion',
            name='comentario',
        ),
        migrations.AddField(
            model_name='confesion',
            name='comentarios',
            field=models.TextField(default='', max_length=420),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confesion.Confesion'),
        ),
    ]
