# Generated by Django 3.0.6 on 2020-05-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confesion', '0003_auto_20200516_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confesion',
            name='comentarios',
        ),
    ]
