# Generated by Django 3.0.6 on 2020-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confesion', '0004_remove_confesion_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='add_comentario',
            field=models.TextField(default='', max_length=420),
        ),
    ]
