# Generated by Django 3.0.6 on 2020-05-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confesion', '0005_comentario_add_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentario',
        ),
        migrations.AddField(
            model_name='confesion',
            name='comentario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='confesion.Comentario'),
            preserve_default=False,
        ),
    ]
