# Generated by Django 3.0.6 on 2020-05-16 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confesion', '0006_auto_20200516_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='add_comentario',
            new_name='contenido',
        ),
        migrations.RemoveField(
            model_name='confesion',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='confesion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='confesion.Confesion'),
            preserve_default=False,
        ),
    ]
